# Generated by Django 3.2.8 on 2022-07-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220722_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_module_perms',
            field=models.BooleanField(default=True),
        ),
    ]
