# Generated by Django 3.2.8 on 2022-07-22 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customuser_has_module_perms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='has_module_perms',
        ),
    ]
